workflows:
  react-native-build:
    name: React Native Build
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      groups:
        - API_KEY
      vars:
        PUBLIC_ENV_VAR: "value here"
      node: 20.18.0
      xcode: latest
      cocoapods: default

    cache:
      cache_paths:
        - ~/.gradle
        - ~/.pub-cache
        - node_modules

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: true

    scripts:
      - echo "Installing dependencies"
      - npm install
      - cd ios && pod install && cd ..
      - echo "Building Android app"
      - npx react-native run-android --variant=release
      - echo "Building iOS app"
      - xcodebuild -workspace ios/PayGuard.xcworkspace -scheme PayGuard -sdk iphoneos -configuration Release archive -archivePath $PWD/build/PayGuard.xcarchive
      - xcodebuild -exportArchive -archivePath $PWD/build/PayGuard.xcarchive -exportOptionsPlist ios/exportOptions.plist -exportPath $PWD/build/PayGuard

    artifacts:
      - build/**/*.aab
      - build/PayGuard/*.ipa
      - build/PayGuard/**/*.app

    publishing:
      email:
        recipients:
          - mprathisha2@gmail.com
      scripts:
        - echo 'Post-publish script completed'
