workflows:
  react-native-build:
    name: React Native Build
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      node: 18.16.0
      xcode: latest
      cocoapods: default
      groups:
        - env_group

    cache:
      cache_paths:
        - ~/.gradle
        - ~/.npm
        - node_modules

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true

    scripts:
      - echo "Installing dependencies"
      - npm install
      - cd ios && pod install && cd ..
      - echo "Building Android release"
      - cd android && ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - mprathisha2@gmail.com
